### ISSUE TITLE
Please remove the project_req.md file

### ISSUE THREAD

**Issue by StraubJones** [electricflannel/fractal-code-challenge#3]
Hey, thanks for the coding challenge! We'll be looking at it more in depth over the next few days. One quick thought I had, though: would you mind removing the project_req.md file? We sometimes will use the same coding challenges for different candidates and we want to make sure somebody else applying for the job doesn't have an unfair advantage knowing what's being asked of them ahead of time.

Thanks again!

**Comment by electricflannel** [comment]
Oops, sorry about that! I removed it as you requested!

**Comment by StraubJones** [comment]
Thanks!
